// test_af_export.cpp — layered Affinity export round trip: build an
// AfLayersDoc in memory, encode it against the template generated by
// afBuildTemplateDoc() (and, when PITTORE_AF_PROBE_DIR is set, against a
// real document's doc.dat), decode the file back and compare. Pixels use
// x257 multiples so the 16→8→16 trip is exact.
#include <cstdio>
#include <string>
#include <vector>

#include "af_probe.h"
#include "engine/io/af_layers.h"
#include "engine/io/af_layers/container/af_archive.h"
#include "engine/io/af_layers/emit/af_write.h"
#include "engine/io/af_layers/graph/af_graph.h"
#include "engine/io/af_layers/graph/af_graph_parser.h"
#include "test_util.h"

namespace {

using pittore::io::AfEncodeResult;
using pittore::io::AfLayer;
using pittore::io::AfLayersDoc;
using pittore::io::AfThumb;
using pittore::io::af_detail::Archive;
using pittore::io::af_detail::emitGraph;
using pittore::io::af_detail::parseGraph;
using pittore::io::afDecodeLayers;
using pittore::io::afEncodeLayers;
using pittore::io::af_detail::Graph;
using pittore::io::af_detail::Node;
using pittore::io::af_detail::Value;

void builtinTemplate();
void clipped();
void fixtureRoundTrip();
void partialTiles();

// Extra coverage: a REAL document's doc.dat used as the template, so the
// writer is exercised against authentic Affinity structure as well as the
// generated one. External fixture fetched separately: PITTORE_AF_PROBE_DIR
// names a directory holding the probe cards. Absent -> empty, callers skip.
// No fixture path is baked into the source.
std::vector<std::uint8_t> templateDocDat() {
    const std::string dir = pittore::probe::probeDir();
    if (dir.empty()) {
        std::printf("  skipping: PITTORE_AF_PROBE_DIR not set\n");
        return {};
    }
    auto bytes = pittore::probe::readFile(dir + "/invert.af");
    if (!bytes) {
        std::printf("  skipping: no invert.af in probe dir\n");
        return {};
    }
    Archive ar = Archive::parse(*bytes);
    const auto* de = ar.head("doc.dat");
    if (!de) {
        std::printf("  invert.af has no doc.dat\n");
        return {};
    }
    return ar.extract(*de);
}

AfLayer pixel(const char* name, int left, int top, int w, int h, int r, int g,
              int b, int indent = 0) {    AfLayer l;
    l.left = left;
    l.top = top;
    l.width = w;
    l.height = h;
    l.opacity = 255;
    l.visible = true;
    l.indent = indent;
    l.name = name;
    l.rgba.assign(std::size_t(w) * h * 4, 0);
    for (std::size_t i = 0; i < std::size_t(w) * h; ++i) {
        l.rgba[i * 4 + 0] = std::uint16_t(r) * 257u;
        l.rgba[i * 4 + 1] = std::uint16_t(g) * 257u;
        l.rgba[i * 4 + 2] = std::uint16_t(b) * 257u;
        l.rgba[i * 4 + 3] = 255u * 257u;
    }
    return l;
}

void run() {
    // Always runs. Everything below needs the external fixture tree.
    builtinTemplate();

    const std::vector<std::uint8_t> tpl = templateDocDat();
    if (tpl.empty()) return;

    AfLayersDoc doc;
    doc.width = 8;
    doc.height = 4;
    doc.depth = 8;
    AfLayer bg = pixel("bg", 0, 0, 8, 4, 200, 10, 20);
    AfLayer grp;
    grp.isGroup = true;
    grp.indent = 0;
    grp.name = "G";
    AfLayer fg = pixel("fg", 2, 1, 4, 2, 30, 40, 250, 1);
    fg.blend = "Multiply";
    fg.opacity = 128;
    fg.masks.push_back({});
    {
        auto& m = fg.masks.back();
        m.left = 2;
        m.top = 1;
        m.width = 4;
        m.height = 2;
        m.px.assign(4u * 2, 255);
        m.px[0] = 0;
    }
    doc.layers = {bg, grp, fg};
    doc.complete = true;

    AfThumb thumb;
    thumb.width = 4;
    thumb.height = 2;
    thumb.rgba.assign(4u * 2u * 4u, 128);
    std::string error;
    auto enc = afEncodeLayers(doc, tpl, thumb, std::string("t"), 1234567890u, &error);
    if (!enc) {
        std::printf("  encode: %s\n", error.c_str());
        CHECK(false);
        return;
    }
    CHECK(!enc->bytes.empty());
    std::printf("  encoded %zu bytes, %zu skipped\n", enc->bytes.size(),
                enc->skipped.size());
    for (const auto& s : enc->skipped) std::printf("    skip: %s\n", s.c_str());
    CHECK(enc->skipped.empty());

    // The container parses and the thumbnail carves back to the thumbnail.
    {
        Archive ar = Archive::parse(enc->bytes);
        CHECK(ar.version == 12);
        CHECK(ar.head("doc.dat") != nullptr);
        auto tp = pittore::probe::thumbPng(enc->bytes);
        CHECK(tp.has_value());
    }

    auto back = afDecodeLayers(enc->bytes, &error);
    CHECK(back.has_value());
    if (!back) {
        std::printf("  decode: %s\n", error.c_str());
        return;
    }
    CHECK_EQ(back->width, 8u);
    CHECK_EQ(back->height, 4u);
    CHECK_EQ(back->layers.size(), 3u);
    if (back->layers.size() != 3) return;
    const auto& L = back->layers;
    CHECK(L[0].name == "bg" && !L[0].isGroup);
    CHECK(L[1].name == "G" && L[1].isGroup);
    CHECK(L[2].name == "fg" && L[2].indent == 1);
    CHECK(L[2].blend == "Multiply");
    CHECK_EQ(L[2].opacity, 128u);
    CHECK(L[2].rgba == fg.rgba);
    CHECK(L[0].rgba == bg.rgba);
    CHECK_EQ(L[2].masks.size(), 1u);
    if (!L[2].masks.empty()) CHECK(L[2].masks[0].px == fg.masks[0].px);

    clipped();
    fixtureRoundTrip();
    partialTiles();
}

// The export template is GENERATED by afBuildTemplateDoc(), not loaded from a
// bundled document, so this runs on a clean checkout with no fixtures at all.
// It asserts two things: the generated graph carries every field
// encodeLayersImpl() patches (a missing one is a silent no-op in mutField()),
// and an encode/decode round trip through it is byte-exact.
void builtinTemplate() {
    const std::vector<std::uint8_t> tpl = pittore::io::afBuildTemplateDoc();
    CHECK(!tpl.empty());
    std::printf("  built-in template: %zu bytes\n", tpl.size());

    Graph g;
    try {
        g = parseGraph(tpl);
    } catch (const std::exception& e) {
        std::printf("  built-in template parse: %s\n", e.what());
        CHECK(false);
        return;
    }

    // The shape findTemplate() walks: root -> DocR -> Chld[0] = spread.
    Node* root = g.root();
    Node* docN = root ? g.child(root, "DocR") : nullptr;
    CHECK(root != nullptr);
    CHECK(docN != nullptr);
    if (!root || !docN) return;
    CHECK(g.field(docN, "DfSz") != nullptr);

    auto spreads = g.children(docN, "Chld");
    CHECK_EQ(spreads.size(), std::size_t(1));
    if (spreads.empty()) return;
    CHECK(g.field(spreads[0], "SprB") != nullptr);
    CHECK(g.field(spreads[0], "MiID") != nullptr);
    const Value* stack = g.field(spreads[0], "Chld");
    CHECK(stack != nullptr && stack->k == Value::K::Array);
    CHECK(stack != nullptr && stack->arr.empty());  // encoder rebuilds it
    CHECK(g.child(root, "CSel") != nullptr);

    // Round trip through the generated template (same document shape run()
    // exercises, so a group/indent path is covered too).
    AfLayersDoc doc;
    doc.width = 8;
    doc.height = 4;
    doc.depth = 8;
    AfLayer bg = pixel("bg", 0, 0, 8, 4, 200, 10, 20);
    AfLayer grp;
    grp.isGroup = true;
    grp.indent = 0;
    grp.name = "G";
    AfLayer fg = pixel("fg", 2, 1, 4, 2, 30, 40, 250, 1);
    fg.blend = "Multiply";
    fg.opacity = 128;
    doc.layers = {bg, grp, fg};
    doc.complete = true;

    AfThumb thumb;
    thumb.width = 4;
    thumb.height = 2;
    thumb.rgba.assign(4u * 2u * 4u, 128);

    std::string error;
    auto enc = afEncodeLayers(doc, tpl, thumb, std::string("builtin"),
                              1234567890u, &error);
    if (!enc) {
        std::printf("  built-in encode: %s\n", error.c_str());
        CHECK(false);
        return;
    }
    CHECK(!enc->bytes.empty());
    CHECK(enc->skipped.empty());
    std::printf("  encoded %zu bytes with the built-in template\n",
                enc->bytes.size());

    auto back = afDecodeLayers(enc->bytes, &error);
    CHECK(back.has_value());
    if (!back) {
        std::printf("  built-in decode: %s\n", error.c_str());
        return;
    }
    CHECK_EQ(back->width, 8u);
    CHECK_EQ(back->height, 4u);
    CHECK_EQ(back->layers.size(), std::size_t(3));
    if (back->layers.size() != 3) return;
    const auto& L = back->layers;
    CHECK(L[0].name == "bg" && !L[0].isGroup);
    CHECK(L[0].rgba == bg.rgba);
    CHECK(L[1].name == "G" && L[1].isGroup);
    CHECK(L[2].name == "fg" && L[2].indent == 1);
    CHECK(L[2].blend == "Multiply");
    CHECK_EQ(L[2].opacity, 128u);
    CHECK(L[2].rgba == fg.rgba);
}

void clipped() {
    const std::vector<std::uint8_t> tpl = templateDocDat();
    if (tpl.empty()) return;
    // Base + clipped child (child placed inside the base) + an unknown
    // blend that must fall back to Normal with a note.
    AfLayersDoc doc;
    doc.width = 300;
    doc.height = 300;
    doc.depth = 8;
    AfLayer base = pixel("base", 10, 10, 280, 280, 100, 150, 200);
    AfLayer clip = pixel("clip", 20, 20, 40, 40, 250, 250, 250);
    clip.clipped = true;
    clip.blend = "Dissolve";
    doc.layers = {base, clip};
    doc.complete = true;
    AfThumb thumb;
    thumb.width = 2;
    thumb.height = 2;
    thumb.rgba.assign(2u * 2u * 4u, 200);
    std::string error;
    auto enc = afEncodeLayers(doc, tpl, thumb, std::string("c"), 7u, &error);
    if (!enc) {
        std::printf("  clipped encode: %s\n", error.c_str());
        CHECK(false);
        return;
    }
    bool noted = false;
    for (const auto& s : enc->skipped)
        if (s.find("clip") != std::string::npos) noted = true;
    CHECK(noted);
    auto back = afDecodeLayers(enc->bytes, &error);
    CHECK(back.has_value());
    if (!back) {
        std::printf("  clipped decode: %s\n", error.c_str());
        return;
    }
    CHECK_EQ(back->layers.size(), 2u);
    if (back->layers.size() != 2) return;
    CHECK(back->layers[1].name == "clip" && back->layers[1].clipped);
    CHECK(back->layers[1].blend == "Normal");
    CHECK(back->layers[1].rgba == clip.rgba);
    // Clip placement is relative to the base: doc-space origin recovered.
    CHECK_EQ(back->layers[1].left, 20);
    CHECK_EQ(back->layers[1].top, 20);
}

void fixtureRoundTrip() {
    // Real-world graph through export: decode a fixture, re-encode it,
    // decode again — structure and pixels must survive. The fixture's own
    // tiles exercise the reader; the re-encode exercises the writer.
    const std::string dir = pittore::probe::afDesignDir();
    if (dir.empty()) return;
    auto bytes = pittore::probe::readFile(dir + "/raster_test.afdesign");
    if (!bytes) {
        std::printf("  skipping: no raster_test.afdesign\n");
        return;
    }
    std::string error;
    auto doc = afDecodeLayers(*bytes, &error);
    CHECK(doc.has_value());
    if (!doc) {
        std::printf("  fixture decode: %s\n", error.c_str());
        return;
    }
    const std::vector<std::uint8_t> tpl = templateDocDat();
    if (tpl.empty()) return;
    AfThumb thumb;
    thumb.width = 2;
    thumb.height = 2;
    thumb.rgba.assign(2u * 2u * 4u, 100);
    auto enc = afEncodeLayers(*doc, tpl, thumb, std::string("r"), 9u, &error);
    if (!enc) {
        std::printf("  fixture encode: %s\n", error.c_str());
        CHECK(false);
        return;
    }
    auto back = afDecodeLayers(enc->bytes, &error);
    CHECK(back.has_value());
    if (!back) {
        std::printf("  fixture re-decode: %s\n", error.c_str());
        return;
    }
    CHECK_EQ(back->width, doc->width);
    CHECK_EQ(back->height, doc->height);
    CHECK_EQ(back->layers.size(), doc->layers.size());
    if (back->layers.size() != doc->layers.size()) return;
    for (std::size_t i = 0; i < doc->layers.size(); ++i) {
        CHECK(back->layers[i].name == doc->layers[i].name);
        CHECK(back->layers[i].isGroup == doc->layers[i].isGroup);
        if (doc->layers[i].isGroup) continue;
        CHECK(back->layers[i].rgba == doc->layers[i].rgba);
        CHECK_EQ(back->layers[i].left, doc->layers[i].left);
        CHECK_EQ(back->layers[i].top, doc->layers[i].top);
    }
}

void partialTiles() {
    // Partial edge tiles (Rect path): 700x700 -> 3x3 grid with ragged edges.
    const std::vector<std::uint8_t> tpl = templateDocDat();
    if (tpl.empty()) return;
    AfLayersDoc doc;
    doc.width = 700;
    doc.height = 700;
    doc.depth = 8;
    AfLayer big;
    big.left = 0;
    big.top = 0;
    big.width = 700;
    big.height = 700;
    big.opacity = 255;
    big.visible = true;
    big.name = "big";
    big.rgba.assign(std::size_t(700) * 700 * 4, 0);
    for (std::size_t i = 0; i < std::size_t(700) * 700; ++i) {
        big.rgba[i * 4 + 0] = std::uint16_t((i * 7) % 256) * 257u;
        big.rgba[i * 4 + 1] = std::uint16_t((i * 13) % 256) * 257u;
        big.rgba[i * 4 + 2] = std::uint16_t((i * 29) % 256) * 257u;
        big.rgba[i * 4 + 3] = 65535u;
    }
    doc.layers = {big};
    doc.complete = true;
    AfThumb thumb;
    thumb.width = 2;
    thumb.height = 2;
    thumb.rgba.assign(2u * 2u * 4u, 100);
    std::string error;
    auto enc = afEncodeLayers(doc, tpl, thumb, std::string("p"), 11u, &error);
    if (!enc) {
        std::printf("  partial encode: %s\n", error.c_str());
        CHECK(false);
        return;
    }
    auto back = afDecodeLayers(enc->bytes, &error);
    CHECK(back.has_value());
    if (!back || back->layers.size() != 1) return;
    CHECK(back->layers[0].rgba == big.rgba);
}

}  // namespace

TEST_MAIN_CALL(run)
